---
version: '3.3'
services:
  zeek-metron:
    image: aswin1906/zeek-metron:6.2-lite
    hostname: zeek-metron
    container_name: zeek-metron
    restart: always
    ulimits:
      memlock:
        soft: -1
        hard: -1
    stdin_open: true
    tty: true
    volumes:
      - ./logs:/pcap:rw
      - ./local.zeek:/usr/local/zeek/share/zeek/site/local.zeek:rw
    cap_add:
      - NET_RAW # allow Zeek to listen to raw packets
      - net_admin # allow Zeek to modify interface settings
    network_mode: "host" # allow Zeek to monitor host network interfaces
    command: -i af_packet::eth0 local /usr/local/nids_zeek_server/index.js # Refer https://github.com/zeek/zeek-af_packet-plugin
    # command: -i af_packet::wlp59s0 local "Site::local_nets += { 192.168.0.100/24 }"
    logging:
      driver: "json-file"
      options:
        max-size: "3m"
        max-file: "1"
    depends_on:
      - kafka

  zookeeper:
    container_name: zookeeper-cntr
    image: confluentinc/cp-zookeeper:7.6.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    restart: always
    ulimits:
      memlock:
        soft: -1
        hard: -1
    stdin_open: true
    tty: true
    networks:
      - zeek-traffic
    logging:
      driver: "json-file"
      options:
        max-size: "3m"
        max-file: "1"
    healthcheck:
      test: echo stat | nc zookeeper-cntr 2181
      interval: 10s
      timeout: 10s
      retries: 3

  kafka:
    # "`-._,-'"`-._,-'"`-._,-'"`-._,-'"`-._,-'"`-._,-'"`-._,-'"`-._,-'"`-._,-
    # An important note about accessing Kafka from clients on other machines: 
    # -----------------------------------------------------------------------
    #
    # The config used here exposes port 29092 for _external_ connections to the broker
    # i.e. those from _outside_ the docker network. This could be from the host machine
    # running docker, or maybe further afield if you've got a more complicated setup. 
    # If the latter is true, you will need to change the value 'localhost' in 
    # KAFKA_ADVERTISED_LISTENERS to one that is resolvable to the docker host from those 
    # remote clients
    #
    # For connections _internal_ to the docker network, such as from other services
    # and components, use kafka:9092.
    #
    # See https://rmoff.net/2018/08/02/kafka-listeners-explained/ for details
    # "`-._,-'"`-._,-'"`-._,-'"`-._,-'"`-._,-'"`-._,-'"`-._,-'"`-._,-'"`-._,-
    #
    container_name: kafka-cntr
    image: confluentinc/cp-kafka:7.6.0
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    restart: always
    ulimits:
      memlock:
        soft: -1
        hard: -1
    stdin_open: true
    tty: true
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-cntr:2181
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka-cntr:9092,EXTERNAL://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - zeek-traffic
    logging:
      driver: "json-file"
      options:
        max-size: "3m"
        max-file: "1"
    healthcheck:
      test: nc -vz kafka-cntr 9092 || exit -1
      interval: 5s
      timeout: 10s
      retries: 10

networks:
  zeek-traffic:
    driver: bridge